stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: demandcluster/anythingllm:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
