stages:
- name: build
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: export TARGETARCH=amd64
  - publishImageConfig:
      dockerfilePath: ./docker/Dockerfile
      buildContext: .
      tag: demandcluster/anythingllm:v1
      pushRemote: true
      registry: harbor.demandcluster.com
timeout: 60
notification: {}
